<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMyqkiol\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMyqkiol/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerMyqkiol.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerMyqkiol\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMyqkiol\appProdProjectContainer([
    'container.build_hash' => 'Myqkiol',
    'container.build_id' => 'd309a4e1',
    'container.build_time' => 1730134018,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMyqkiol');
