<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMqvby3k\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMqvby3k/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMqvby3k.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMqvby3k\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerMqvby3k\appDevDebugProjectContainer([
    'container.build_hash' => 'Mqvby3k',
    'container.build_id' => '07a1a4b2',
    'container.build_time' => 1732299299,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMqvby3k');
