<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKdjcvdd\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKdjcvdd/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKdjcvdd.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKdjcvdd\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKdjcvdd\appDevDebugProjectContainer([
    'container.build_hash' => 'Kdjcvdd',
    'container.build_id' => '6bf57910',
    'container.build_time' => 1731688988,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKdjcvdd');
