<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRi5q1x9\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRi5q1x9/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRi5q1x9.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRi5q1x9\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRi5q1x9\appDevDebugProjectContainer([
    'container.build_hash' => 'Ri5q1x9',
    'container.build_id' => 'c564f755',
    'container.build_time' => 1731604782,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRi5q1x9');
